
---
- hosts: localhost
  tasks:
      - name: crea aviso de error en /tmp/
        file:
            path: /tmp/fallo
            state: touch



      - name: send a message to chat in playbook
        telegram:
          token: '789814150:AAE86c3jBVW5v2EQ2uEIZhZ_vxKIIhYXt0U'
          chat_id: 519410943
          msg: Ansible task finished
