---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: consulta kernel
    shell: "uname -a  |  awk '{print $2}' "
    register: kernel_ver
    
  - debug: 
     msg: " {{ kernel_ver.stdout }} "
...
