---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: consulta kernel
    shell: "uname -a  |  awk '{print $3}' "
    register: kernel_ver
    


  - name: consulta hostname
    shell: "uname -a  |  awk '{print $2}' "
    register: hostname_ver
    
  - debug: 
     msg: " el host {{ hostname_ver.stdout }} tiene el kernel {{ kernel_ver.stdout }} "
...
