
---
- hosts: localhost
  tasks:
      - name: crea aviso de error en /tmp/
        file:
            path: /tmp/fallo_ansible_{{ansible_date_time.date}}.log
            state: touch



      - name: send a message to chat in playbook
        telegram:
          token: '789814150:AAE86c3jBVW5v2EQ2uEIZhZ_vxKIIhYXt0U'
          chat_id: 519410943
          msg: "Ansible {{ tower_workflow_job_name }}  falló a las {{ansible_date_time.date}} 

