---
- hosts: Linux
  tasks:
  - name: elimina el usuario toxico
    user:
      name: toxico
      state: absent
      
- hosts: haproxycentos
  tasks:
  - name: frenar haproxy en el balanceador
    systemd:
      name: haproxy.service
      state: stopped

- hosts: webservers
  tasks:
  - name: desinstala Httpd
    yum:
      name: httpd
      state: absent
    
- hosts: RHEL
  tasks:
  - name: poner SElinux en permissive
    selinux:
      policy: targeted
      state: permissive
      
- hosts: Linux
  tasks:
  - name: instala nmap
    package:
      name: nmap
      state: present
