

# borra el usuario toxico en caso de existir
- hosts: Linux
  tasks:
  - name: elimina el usuario toxico
    user:
      name: toxico
      state: absent

- hosts: webservers
  tasks:
  - name: desinstala httpd y remueve puerto 80 del firewall
    package:
      name: httpd
      state: absent
    firewalld:
      service: http
      permanent: yes
      state: disabled
      
 
- hosts: haproxycentos
  tasks:
 - name: frenar haproxy en balanceador
  systemd:
    state: stopped
    name: haproxy.service
