---
- hosts: Linux
  tasks:
  - name: elimina el usuario toxico
    user:
      name: toxico
      state: absent
      
- hosts: haproxycentos
  tasks:
  - name: frenar haproxy en el balanceador
    systemd:
      name: haproxy.service
      state: stopped

- hosts: webservers
  tasks:
  - name: desinstala httpd y quita regla del fw
    package:
      name: httpd
      state: absent
    firewalld:
      service: http
      permanent: yes
      state: disabled
