---
- hosts: Linux
  tasks:
  - name: elimina el usuario toxico
    user:
      name: toxico
      state: absent
      
- hosts: haproxycentos
  tasks:
  - name: frenar haproxy en el balanceador
    systemd:
      name: haproxy.service
      state: stopped

