---
- hosts: RHEL
  tasks: 
    name: Se define estado hardened para SElinux en grupo RHEL
    selinux:
      policy: targeted
      state: enforcing

#- hosts: Linux
#  tasks:
#    name: desinstalar gcc a traves de package a todos los linux
#      package:
#        name: gcc
#        state: absent


#- hosts: Linux
#  tasks:
#    name: Se remueve nmap en todos los servidores Linux
#      package:
#        name: nmap
#        state: absent
...
