---
# hardening para el ambiente laboratorio demo

- hosts: Linux
  tasks: 
    name: Se remueve GCC en servidores grupo Linux
    package:
      name: gcc
      state: absent


- hosts: RHEL
  tasks: 
    name: Se define estado hardened para SElinux en grupo RHEL
    selinux:
      policy: targeted
      state: enforcing



#- hosts: Linux
#  tasks:
#    name: Se remueve nmap en todos los servidores Linux
#      package:
#        name: nmap
#        state: absent
...
