---
- hosts: RHEL
  gather_facts: no
  tasks:
  - name: Se valida estado de SELINUX
    selinux:
      policy: targeted
      state: enforcing

- hosts: debian
  gather_facts: no
  tasks:
  - name: Se valida estado de UFW
    ufw:
      state: enabled

       
- hosts: Linux
  gather_facts: no
  tasks:
  - name: Se remueve nmap en todos los servidores Linux
    package: 
      name: nmap
      state: absent

#- hosts: Linux
#  tasks:
#    name: desinstalar gcc a traves de package a todos los linux
#      package:
#        name: gcc
#        state: absent


#- hosts: Linux
#  tasks:
#    name: Se remueve nmap en todos los servidores Linux
#      package:
#        name: nmap
#        state: absent
...
