---
- hosts: webservers
  become: yes
  tasks:
  - name: delegacion
    debug:
      msg: "delegando facts de webservers a haproxycentos1 "
    delegate_to: HaproxyCentos1
    delegate_facts: True
    loop: "{{groups['webservers']}}"

- hosts: HaproxyCentos1
  tasks:
  - name: creacion del archivo de configuracion en base al template jinja
    template:
      src: haproxy.jinja2
      dest: /etc/haproxy/haproxy.cfg
...
