
- hosts: webservers
  tasks:
  - name: crear linea en haproxy
    debug:
      msg: "saludame cabron"
      
- hosts: localhost
  tasks:
  - name: probar si sale
    debug:
      msg: "{{ hostvars[MinionCentos1]['ansible_hostname']}}"
      
      
      
      #['ansible_default_ipv4.network']}}:80 check"



#- hosts: webservers
#  tasks:
#  - name: crear linea en haproxy
#    debug:
#      msg: "server {{ ansible_hostname }} {{ ansible_default_ipv4.network }}:80 check" 
#    register: thor
