- hosts: webservers
  tasks:
   - name: crear linea en haproxy
     debug:
       msg: "server {{ ansible_hostname }} {{ ansible_default_ipv4.network }}:80 check" 
     register: nombreprueba
     
 - hosts: localhost
  - name: imprimir
    debug: nombreprueba
      msg: "{{ nombreprueba.[webservers}}}"
