---
- hosts: localhost
  tasks:
      - name: crea aviso de tarea finalizada en /tmp/log_ansible 
        lineinfile:
            path: /home/gabriel/log_ansible
            line: Tarea Ansible Finalizada Satisfactoriamente el {{ansible_date_time.date}} por {{ ansible_user }}
            create: yes


      - name: enviar mensaje via Telegram
        telegram:
          token: '789814150:AAE86c3jBVW5v2EQ2uEIZhZ_vxKIIhYXt0U'
          chat_id: 519410943
          msg: Tarea Ansible Finalizada Satisfactoriamente el {{ansible_date_time.date}} por {{ ansible_user }} 
