---
- hosts: localhost
  tasks:
      - name: crea aviso de tarea finalizada en /tmp/
        file:
            path: /tmp/finaliza_ok
            state: touch



      - name: enviar mensaje via Telegram
        telegram:
          token: '789814150:AAE86c3jBVW5v2EQ2uEIZhZ_vxKIIhYXt0U'
          chat_id: 519410943
          msg: " {{ tower_job_template_name }} {{tower_job_id }} Finalizó Satisfactoriamente el {{ansible_date_time.date}} por {{ tower_user_name }} "
