## Scrape Config - Tower
  - job_name: 'tower'
	metrics_path: /api/v2/metrics
	scrape_interval: 5s
	scheme: https
	bearer_token: MuVRSLoLfQO0Vh6wUuyz4oGHBNdhi0
	static_configs:
	- targets:
  	  - tower.customer.com

## Add Node Exporter
  - job_name: 'tower-01'
	scrape_interval: 5s
	static_configs:
	- targets: ['192.168.122.36:9100']

  - job_name: 'tower-02'
	scrape_interval: 5s
	static_configs:
	- targets: ['192.168.122.36:9100']

  - job_name: 'tower-db-01'
	scrape_interval: 5s
	static_configs:
	- targets: ['192.168.122.36:9100']
