---
- hosts: haproxycentos1
  tasks:
  - name: Instalar haproxy en el Host
    package:
       name: haproxy
       state: present

- hosts: haproxycentos1
  tasks:
  - name: iniciar haproxy en el balanceador
    systemd:
       name: haproxy.service
       state: started
      
- hosts: haproxycentos1
  tasks:
  - name: habilitar puerto 80 en el firewalld
    firewalld:
      service: http
      permanent: yes
      state: enabled
      
- hosts: haproxycentos1
  tasks:
  - name: reiniciar firewalld para tomar cambios
    service:
      name: firewalld
      state: restarted
...
