---
    

- hosts: localhost
  tasks:
  - name: clonar el repo a local
    git:
      repo: 'https://github.com/gbenselum/laboratorio_ansible.git'
      dest: /home/gabriel/repo
      clone: yes

- hosts: localhost
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /home/gabriel/repo/haproxy.cfg
        dest: /etc/haproxy.conf
        owner: root
        group: root
        mode: '0644'



- hosts: haproxycentos1
  tasks:
  - name: Instalar haproxy en el Host
    package:
       name: haproxy
       state: present

- hosts: haproxycentos1
  tasks:
  - name: iniciar servicio haproxy
    systemd:
       name: haproxy.service
       state: started
      
- hosts: haproxycentos1
  tasks:
  - name: habilitar puerto 80 en el firewalld
    firewalld:
      service: http
      permanent: yes
      state: enabled
      
- hosts: haproxycentos1
  tasks:
  - name: reiniciar firewalld para tomar cambios
    service:
      name: firewalld
      state: restarted

- name: Copy file with owner and permissions
  copy:
    src: /var/lib/awx/projects/_6__github_lab_test_drive/haproxy.cfg
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: '0644'



...
