---

- hosts: haproxycentos1
  gather_facts: no
  tasks:
  - name: Instalar haproxy en el Host
    yum:
      name: haproxy
      state: present


  - name: iniciar servicio haproxy
    systemd:
      name: haproxy.service
      state: started
      
  - name: habilitar puerto 80 en el firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
      
  - name: reiniciar firewalld para tomar cambios
    service:
      name: firewalld
      state: restarted

...
