---
- hosts: debian
  gather_facts: no
  tasks:
    - name: se bloquea desde variable la IP "{var_ipadd}"
      ufw:
        rule: deny
        proto: all
        src: {var_ipadd}
        comment: bloqueo IP {var_ipadd} definido por regla ansible
